apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-tls
  namespace: traefik
spec:
  secretName: homelab-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.homelab.local"
    - "homelab.local"
